### ISSUE TITLE
bunch of issues

### ISSUE THREAD

**Issue by Guria** [cerebral-legacy/cerebral-debugger#13]
Tested on latest todomvc demo with immutable model:
- [x] clicking on  state path in signal tab hides signals tab on the wide mode when model is not a tab(edited)
- [x] there is no way to reset highlight of state path
- [x] components tab doesn't updated when app just loaded
- [x] possibly we should reset components tab on app reload
- [x] reset all state doesn't reset state on app
- [x] time travel messes the app (possibly because of previous)

**Comment by christianalfoni** [comment]
Last two will be part of next release :)
