### ISSUE TITLE
Debugger Shows Array Modification More Than Once

### ISSUE THREAD

**Issue by YaguangZhang** [cerebral-legacy/cerebral-debugger#14]
It seems that changes to an array in the state (push, merge, etc) are replayed in the debugger every time any other signal is fired. The actual state only has the change once.

For example, in the `cerebral-website-tutorial-next-react` repo, `react` branch, if you add an item to the todo list that is successfully submitted to the server and then type in the input box you will see the issue. The submitted item in the `app.items` array appears over and over again, once for each onChange event of the input. However, if you console.log the state the item is in the array only once.

This seems related to the newly released debugger (July 15th, version .49).

You can see a `copy signals` dump here:  https://gist.github.com/YaguangZhang/98405f575b6e35dc6e2bee0e9697f0b7

**Comment by christianalfoni** [comment]
Thanks a bunch for a great error report! Yes, there was a bit of a drastic change to debugger to fix a bug, but it seems to have introduced a new bug. But we are on the right track to handle it correctly, let me look at this ASAP :)

**Comment by christianalfoni** [comment]
Okay I have deployed a new version of debugger which should rebuild the state correctly, version 0.50. Thanks again for error report :)

**Comment by abalmos** [comment]
Thanks @christianalfoni !

**Comment by YaguangZhang** [comment]
Thanks @abalmos @christianalfoni !
