### ISSUE TITLE
Baobab monkey properties are not property displayed in the Model tab.

### ISSUE THREAD

**Issue by kgdev** [cerebral-legacy/cerebral-debugger#8]
Monkey properties are not properly evaluated and are null or empty shown in the Model tab.

christianalfoni - Today at 6:05 PM
@kg Yeah, we had a couple of iterations on that. I do not quite remember the reason, but it is related to how Baobab creates these values. It is not serializable. Which is needed to pass the info to the Debugger. Though I believe this can be revisited now as the logic in the debugger has changed. Could you create an issue on the cerebral-debugger-prototype repo? 😃 We are changing the name of that soon, but yeah, that is where it belongs now

**Comment by kgdev** [comment]
use state.export() instead of state.get()?

**Comment by christianalfoni** [comment]
Will look into this as soon as I can :) But good suggestion!
